ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webapp.urls')),
    path('accounts/', include('allauth.urls')),
  
]

webapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import path, include 
from django.conf.urls.static import static
# from webapp.views import home,itemdetails
from webapp.views import HomeView,ItemDetailView,add_to_cart,about_us,contact,cart_item,profile


app_name='webapp'
urlpatterns = [
    # path('',home,name='homapage')
    path('home/', HomeView.as_view(),name='home'),
    path('product/<slug>/',ItemDetailView.as_view(),name='product'),
    path('add_to_cart/<slug>/',add_to_cart,name='add_to_cart'),
    path('about/',about_us,name='about'),
    path('contact/',contact,name='contact'),
    path('cart/',cart_item,name='cart_item'),
    path('accounts/profile/',profile,name='profile'),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User

Category_Choice=(
    ('sh','shoe'),
    ('ha','hat'),
    ('wa','watch'),
)

class Item(models.Model):
    title=models.CharField(max_length=100)
    price=models.FloatField()
    discount_price=models.FloatField(blank=True, null=True)
    category=models.CharField(choices=Category_Choice,max_length=3 ,default='shoe')
    slug=models.SlugField(default='shoe')
    description=models.TextField()
    on_stock=models.IntegerField(default=1)
    item_make=models.CharField(blank=True,null=True,max_length=100)
    image=models.ImageField(default='item.jpg',upload_to='item_images/')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('webapp:product',kwargs={ 'slug':self.slug})    
    
    def get_add_to_cart_url(self,slug):
        return reverse('webapp:add_to_cart',slug=self.slug)       

 

class OrderItem(models.Model):
    ordered=models.BooleanField(default=False)
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE ,blank=True,null=True)
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    def __str__(self):
        return f"{self.quantity} of  {self.item.title}"

class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    item=models.ManyToManyField(OrderItem)
    start_date=models.DateTimeField(auto_now_add=True)
    ordered=models.BooleanField(default=False)
    # ordered_date=models.DateTimeField(date.now)


    def __str__(self):
       return self.user.username

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='item.jpg',upload_to='profile_images/')


    def __str__(self):
        return (self.user.username)
    

ecommerce/views.py
from django.shortcuts import render




     

webapp/views.py
from django.utils import timezone
from django.shortcuts import render,get_object_or_404
from django.views.generic import ListView,DetailView
from webapp.models import Item,OrderItem,Order
from django.shortcuts import redirect

# def home(request):
#     context={
#         'item':Item.objects.all
#     }
#     return render(request,'webapp/item_list.html',context)
# def itemdetails(request,id):
#     item=Item.Objects.all(id=id)
#     context={
#         'item':item
#     }
#     return render(request,'webapp/item_details.html',context)


class HomeView(ListView):
    model=Item
    template_name='item_list.html'


class ItemDetailView(DetailView):
    model=Item
    template_name='webapp/product.html'    

def add_to_cart(request,slug):
    item=get_object_or_404(Item,slug=slug)    
    order_item=OrderItem.objects.get_or_create(item=item)
    order_qs=Order.objects.filter(user=request.user,ordered=False)

    if order_qs.exists():
        order=order_qs[0]
        if order.item.filter(item__slug=item.slug).exists():
            order_item.quantity +=1
            order_item.save
        else:
            order.items.add(order_item)    
    else:
        ordered_date=timezone.now()
        order=Order.objects.create (user=request.user,ordered_date=ordered_date)  
        order.item.add(order_item)  
        return redirect("webapp:product",kwargs={'slug':slug})   
def about_us(request):
    return render(request,'about_us1.html')

def contact(request):
    return render(request,'contact_us.html') 
def cart_item(request):
    return render(request,'cart/cart_list.html')       
def profile(request):
    return render(request,'accounts/profile.html') 

templates/About_us.html
{% extends 'base.html %}

{% block content%}
<style>
.about_us{
    display:flex;
    flex-direction: column;
    background:rgb(3, 153, 212);
}
.about_left{
    width:50%;
    height:70%;
}
.about_right{
    width:50%;
    height:70%;
}


</style>
    <div class="about_us">
        <div class="about_left">
            <h2>Who are we?</h2> 
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                     Recusandae quo tenetur earum. Sapiente pariatur neque adipisci 
                    iusto quos ipsa quasi aspernatur doloremque nihil, atque saepe reiciendis iure facilis soluta eveniet.</p>
            <h2>What we do</h2> 
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                         Repellendus et voluptas molestias fugit debitis minima ex maiores reiciendis 
                        cupiditate alias doloribus mollitia amet ratione deserunt quam, cum animi unde voluptate.</p>
        </div>
        <div class="about_right">
            <h2>Where are we?</h2>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ut facilis alias rem dolore nisi, 
                    corrupti neque ad quidem vitae,
                     aperiam harum nostrum iusto adipisci illo ab cum perspiciatis odit possimus!</p>
            <h2>What are our products</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                         Eum nesciunt sint id natus architecto! Expedita at nihil, recusandae amet iste perferendis. 
                         At quam dignissimos perspiciatis iure tenetur nostrum sint repellat.</p>
        </div>
    </div>    

{% endblock%}

templates/about_us1.html
{% extends 'base.html'%}
{% block content %}
<style>
    *{
        padding:0px;
        margin:0px;
        box-sizing: border-box;
    }
.container{
    /* height:120%; */
    display:flex;
    flex-direction: column;
    /* margin:10px; */
    justify-content: center;
    align-items: center;
    background: grey;
    
}
.content_left{
    width:50%;
    height:60%;
    display:flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}
.content_right{
    width:50%;
    height:60%;
    display:flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}
h2{
    font-size:30px;
}
p{
    margin:10px;
    font-family:Georgia, 'Times New Roman', Times, serif;
}
h3{
    margin:10px;
    font-family:Georgia, 'Times New Roman', Times, serif;
    font-size:35px;
    color:white;
}
.main{
    height:100%;
    display:flex;
    flex-direction: row;
    margin:40px;
}
</style>
<body>
    <div class="container">
                <H3>THIS IS ALL ABOUT US</H3>
       <div class="main">        
        <div class="content_left">
                <h2>WHO ARE WE?</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Suscipit soluta temporibus
                 quam ex dolor error eligendi corrupti incidunt,
                sunt corporis molestias earum commodi minus ipsum esse nesciunt rerum et tempora?</p>
                <h2>WHAT DO WE DO?</h2>
             <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A voluptatibus
                  laboriosam cupiditate doloremque neque voluptate maxime, exercitationem atque delectus earum reiciendis? 
                 Natus dolor neque accusantium fugit iste atque pariatur eaque.</p> 
                <h2>WHERE ARE WE LOCATED?</h2>  
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo neque,
                   doloribus esse quos rem iure odit ipsum eligendi tempore. Sapiente quas incidunt sunt,
                   harum expedita optio consectetur tempora voluptates libero.</p>   
        </div>
        <div class="content_right">
                <h2>WHAT DO WE DO?</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Suscipit soluta temporibus
                        quam ex dolor error eligendi corrupti incidunt,
                       sunt corporis molestias earum commodi minus ipsum esse nesciunt rerum et tempora?</p>
                       <h2>WHAT DO WE DO?</h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A voluptatibus
                         laboriosam cupiditate doloremque neque voluptate maxime, exercitationem atque delectus earum reiciendis? 
                        Natus dolor neque accusantium fugit iste atque pariatur eaque.</p>
                        <h2>WHAT DO WE DO?</h2>   
                     <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Explicabo neque,
                          doloribus esse quos rem iure odit ipsum eligendi tempore. Sapiente quas incidunt sunt,
                          harum expedita optio consectetur tempora voluptates libero.</p> 
                        </div> 
        </div>
    </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html'%}
{% load static %}

{% block content %}
<style>
    .container{
        /* width:60vw; */
        /* height:70vh; */
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;

    }
    .jumbotron{
        display:flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background:grey;
        width:60vh;
        height:60vh;
        border-radius: 250px;
    }
    .left{
        width:10vw;
        height:20vh;
        background: black;
        margin-left:5px;
    }
    .details{
        display:flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        background:grey;
        width:20vw;
        height:20vh;

    }
    .total{
    display:flex;
    flex-direction: column;
    }
    .section{
        display:flex;
        flex-direction: column;
        width:30vw;
        height:20vh;
        justify-content: center;
        align-items: center;

    }
    .username{
        margin:10px;
        text-align: center;
        width:60%;
        height:50px;
        border-radius: 10px;
        border:1px solid black;
    }
    .email{
        margin:10px;
        text-align: center;
        width:60%;
        height:50px;
        border-radius: 10px;
        border:1px solid black;
    }
    .btn{
        background: green;
        margin-bottom: 20px;
        border-radius: 10px;
        width:100px;
        height:40px;
        border:1px solid rgb(49, 48, 48);
    }
</style>

    <div class="container">
        <div class="jumbotron">   
            <div class="details">
                <div class="left">
                    <img src="" alt="img">
                </div>
                <div class="total">
                        <p>{{user.username}}</p>
                        <p>{{user.email}}</p>
                </div>
            </div>
            <div class="section">
                <input type="text" class="username" value="username">
                <input type="email" class="email" value="email">
            </div>
            <button class="btn">
                    update
            </button>
        </div>


    </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <link rel="stylesheet" href="{% static '/css/fontawesome/css/all.css' %}">
     <title>Ecomapp</title>
    {%block extra_css%}
   
    {%endblock extra_css%}
</head>
<body>

    <div class="header">
        <div class="title">
            <li><a href="#">Hello</a></li>
        </div>
        <div class="pages">
            <li><a href="{% url 'webapp:home' %}">Home</a></li>
            <li><a href="{% url 'webapp:about' %}">About us</a></li>
            <li><a href="{% url 'webapp:contact' %}">Contact us</a></li>
            <li><a href="#">shoe</a></li>
            <li><a href="#">jacket</a></li>
            <li><a href="#">Hats</a></li>
        </div>


        <div class="logs">
                <div class="cart_no">12</div>
                <li><a href="{% url 'webapp:cart_item' %}">cart</a></li>
                {% if user.is_authenticated %}
                    <li><i class="fa fa-sign-out" aria-hidden="true"></i>
                        <a href="# ">logout</a></li>
                {% else %}
                     <li><a href="#"></a>">login</a></li>
                     <li><a href="#"></a>">register</a></li>
               {% endif %}
            </div>
    </div>
    {% block content %}
    {% endblock content %}
    <div class="footer">
        <div class="contact">
            <h1>Contact Us</h1>
            Hello@gmail.com</br>
            0200284635</br>
            facebook:hellolad</br>
            instagram:@hellolad
        </div>
        <div class="about_us">
            <h1>About Us</h1>
            What do we do?</br>
            What are our main products?</br>
            How doe we deliver products?</br>
            How long does it take to get your product?
        </div>
        <div class="help">
            <h1>Help</h1>
            How do i shop?</br>
            How do i pay?</br>
            How do i get my products?
        </div>
    </div>
</body>

</html>

templates/cart/cart_list.html
{% extends 'base.html' %}
{% block content %}
<style>
.cart_list{
    width:100%;
    height:70vh;
    display:flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}    
.cart_item_title{
    display: flex;
    flex-direction: row;
    height:100%;
    width:60%;
}
thead>th,tbody>td{
    margin:20px;
}

</style>

    <div class="cart_list">
        {% if item %}
        {% for item in cart_obaject_list%}
        <div class="cart_item_title">
            <table>
                <thead>
                    <th>title</th>
                    <th>quantity</th>
                    <th>amount</th>
                </thead>

                <tbody>
                    <td>{{item.title}}</td>
                   <!-- x<td>{{2}}</td> -->
                    <td>{{item.price}}</td>
                </tbody>
                <!-- <p>{{item.total}}</p> -->
            </table>
        </div>
        {% endfor %}
        {% else%}
        <table>
                <thead>
                    <th>title</th>
                    <th>quantity</th>
                    <th>amount</th>
                </thead>
                <tr>
                    <td>watch</td>
                   x<td>2</td>
                    <td>200</td>
                </tr>
            </table>
            <div class="total">
                    <p>Total</p>
            </div>
        </div>
        {% endif%}

    </div>
{% endblock%}

templates/contact_us.html
{% extends 'base.html' %}
{% block content %}
<style>
    *{
        margin:0;
        padding:0;
        box-sizing: border-box;
    }
    body{
        color: red;
        background:grey;
    }
    .container{
        width:100%;
        /* height:80vh; */
        display:flex;
        justify-content: center;
        align-items: center;
    }
    .contact_form{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        background: rgb(105, 72, 72);
        width:70%;
        height:100%;
    }
    p,h2{
        font-size: 33px;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        display: flex;
        justify-content: center;
        align-items: center;
        /* color:red; */
    }
    .info_contact{
        display:flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        height:30%;
        width:70%;
    }
    button{
        background:green;
        width:70%;
        height:40px;
        border-radius:20px;
        margin-top:10px;
        border:1px solid greenyellow;
    }

    .text{
        width:50%;
        height:60px;
        text-align: center;
    }
    .text_email{
        width:50%;
        height:60px; 
        text-align: center;
    }
    .messages{
        width:70%;
        height:90px; 
        text-align: center;
        border-radius: 10px;
    }


</style>
<body>
    <div class="container">
            <form action="Post" class="contact_form">
                    <p>Contact us</p>
                    <h2>Hola at us</h2>
                    <div class="info_contact">
                        <input type="text" class="text" value=Name>
                        <input type="email" class="text_email" value=Email>
                    </div>
                    <input type="text" class="messages" id="message" Value=Messages>
            
                    <button type="submit">Send</button>
                </form>
    </div>

{% endblock%}

templates/webapp/item_list.html
{% extends 'base.html'%}
{% block content%}
<style>
.container{
    color:black;
    height:70vh;
}
.main{
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    flex-wrap: wrap;
}
.card{
    height:350px;
    width:220px;
    margin:10px;
    /* border:1px solid grey; */
    display:flex;
    justify-content:center;
    /* align-items: center; */
    flex-direction: column;
    /* background:rgb(14, 9, 9); */
   
}
.card:hover{
    height: 370px;
    width:250px;

}
/* a{
    color:black;
} */

.qty_cart{
    width:100%;
    display: flex;
    align-items: center;
    justify-content: center;
    /* margin:10px; */
    flex-direction: row;
    text-align: center;
   
}
.cart_btn{
    background:rgb(5, 196, 5);
    width:100%;
    height:40px;
    margin: 5px;
    display:flex;
    /* text-align: center; */
    justify-content: center;
    align-items: center;
}
.qty{
    border:1px solid black;
    width:100%;
    height:40px;
    margin:5px;
    /* text-align: center; */
    display:flex;
    justify-content: center;
    align-items: center;
}
.price{
    display:flex;
    flex-direction: column;
    margin-bottom:5px;
}
.image_item{
    /* width:400px; */
    height:400px; 
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    /* background:rgb(7, 197, 7); */
}
.tittle{
    display:flex;
    justify-content: center;
    align-items: center;
}
.item_price{
    display:flex;
    flex-direction: row;

}
.item_on_stock{
    display:flex;
    flex-direction: row;
    
}
.inner_item_onstock{
    margin-left:15px;
}
.inner_item_price{
    margin-left:15px;
}
</style>
<div class="container">
    <div class="main">
     {% if object_list %}
        {% for items in object_list %}
            <div class="card">
                <div class="tittle">
               <h2><a href="{{items.get_absolute_url}}">{{items.title}}</a></h2>
            </div>
               <div class="image_item">
                   <!-- <img src="{{items.image" alt="item img"> -->
                   <img src="{{ items.image.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" /> 
               </div>

               <div class="item_on_stock">
                    <!-- <div><i class="fas fa-skiing fa-fw" style="background:SkyBlue"></i> Skiing</div> -->
                    <i class="fa fa-cubes fa-3x" aria-hidden="true" ></i>
                    <div class="inner_item_onstock">
                    on stock:<p> <a href="{{items.get_absolute_url}}">{{items.on_stock}}</a> </p>
                     </div>
              </div>
               
             
               <div class="price">
                  
                {% if items.discount_price %} 
                     <!-- <del>{{items.price}}</del> -->
                     <div class="item_price">
                        <i class="fa fa-shopping-cart fa-3x"  aria-hidden="true"></i>
                       <div class="inner_item_price">
                            Price<p> <a href="{{items.get_absolute_url}}"> {{items.discount_price}}</a> </p>
                       </div>
                    </div>
                    

                {% else %}
                <div class="item_price">
                    <i class="fa fa-shopping-cart fa-3x"  aria-hidden="true"></i>
                   <div class="inner_item_price">
                        Price<p> <a href="{{items.get_absolute_url}}"> {{items.price}}</a> </p>
                   </div>
                </div>

                {% endif %}
               </div>  

                 <div class="qty_cart">
                        <div class="qty">Qty  1{{items.quantity}}</div>
                        <div class="cart_btn"><a href="{{items.get_add_to_cart_url}}">add to cart</a></div>
                 </div>
            </div>
   
        {% endfor%}
     {% else%}  
     <p>no record found</p> 
     {% endif %}
    </div>
</div>
{% endblock content%}

templates/webapp/product.html
{% extends 'base.html'%}
{%block content%}
<style>
.detail_container{
    height:70vh;
    display:flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}
.item_detail_content{
    display:flex;
    flex-direction: column;
    width:40%;
    height:100%;
    justify-content:start ;
    /* align-items:center ; */
}
.extra_content{
    border-top: 1px solid black;
    height:30%;
    display:flex;
    flex-direction: center;
    width:50%;
    margin:20px;
    justify-content: center;
    align-items: center;
}
.detail_image{
    /* margin-left: 40px; */
    width:30%;
    background:grey;
    height:100%;
}
.main_details{
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    margin:10px;
}
</style>
<div class="detail_container">
    <div class="main_details">
        <div class="detail_image">
             <img src="{{ items.image.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" /> 
        </div>
        <div class="item_detail_content">
            <h2>Title</h2>
                <p>{{item.title}}</p>
            <h2>Description</h2>
             <p>{{item.description}}</p>
            <h2>item price:</h2>
            <p>{{item.price}}</p>
        {% if discount_price %}
            <h2>privious price</h2>
            <del>{{ item.discount_price}}</del>
        {% endif %}

        </div>
    </div>
    <div class="extra_content">
            <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
            Aperiam alias exercitationem praesentium itaque repellendus, 
            magni cumque vitae cupiditate ipsa consectetur consequatur pariatur debitis vero necessitatibus
             in porro repellat hic? Reprehenderit?
            </p>
        </div>

    </div>

</div>
{% endblock %}